#include <string.h>
#include <mono-wasi/driver.h>
#include <mono/metadata/assembly.h>
#include <assert.h>

void load_runtime();
// This symbol's implementation is generated during the build
const char* dotnet_wasi_getentrypointassemblyname();

// These are generated by EmitWasmBundleObjectFile
const char* dotnet_wasi_getbundledfile(const char* name, int* out_length);
void dotnet_wasi_registerbundledassemblies();

MonoMethod* method_HandleIncomingRequest;
MonoObject* interop_instance = 0;

int is_runtime_loaded = 0;

__attribute__((export_name("run_e")))
char* run_e() {
   load_runtime();

    if (!method_HandleIncomingRequest) {
        method_HandleIncomingRequest = lookup_dotnet_method("test.dll", "", "Interop", "HandleIncomingRequest", -1);
        assert(method_HandleIncomingRequest);
    }

    void* method_params[] = {};
    MonoObject* exception;
    MonoObject *result = mono_wasm_invoke_method(method_HandleIncomingRequest, NULL, method_params, &exception);
    assert(!exception);

//     char* bool_result = (char*) mono_object_unbox(result);
//     return bool_result;
return "WOW";
}

__attribute__((__import_module__("wapc"), import_name("wow"))) extern
void wow();

void load_runtime() {
    if(!is_runtime_loaded) {
        is_runtime_loaded = 1;
        dotnet_wasi_registerbundledassemblies();

        mono_wasm_load_runtime("", 0);
        mono_add_internal_call("Interop::Wow", wow);

    }
}
