[package]
name = "rust_example"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["cdylib"]

[dependencies]
#robotchallenge = { path = "../../libs/rust_robotchallenge/" }
robotchallenge = "0.0.2"
