name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    environment: Deploy to undrfin.de
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Populate env file
      run: |
        cp .env.example .env
        sed -i 's/DOMAINS=""/DOMAINS="${{ secrets.DOMAINS }}"/g' .env
        sed -i 's/CERTBOT_EMAILS=""/CERTBOT_EMAILS="${{ secrets.CERTBOT_EMAILS }}"/g' .env
        sed -i 's/GH_CLIENT_ID=""/GH_CLIENT_ID="${{ secrets.GH_CLIENT_ID }}"/g' .env
        sed -i 's/GH_CLIENT_SECRET=""/GH_CLIENT_SECRET="${{ secrets.GH_CLIENT_SECRET }}"/g' .env
        APP_API_ENDPOINT=$(sed 's:/:\\/:g' <<< ${{vars.APP_API_ENDPOINT}})
        sed -i "s/APP_API_ENDPOINT=\"\"/APP_API_ENDPOINT=\"$APP_API_ENDPOINT\"/g" .env
    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.DOMAINS }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.SSH_USER }}
        docker_compose_prefix: undrfinde
        docker_compose_filename: docker-compose.yml

