name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    environment: Deploy to undrfin.de
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Populate env file
      run: |
        cp .env.example .env
        sed -i 's/DOMAINS=""/DOMAINS="${{ secrets.DOMAINS }}"/g' .env
        sed -i 's/CERTBOT_EMAILS=""/CERTBOT_EMAILS="${{ secrets.CERTBOT_EMAILS }}"/g' .env
        sed -i 's/POSTGRES_USER=""/POSTGRES_USER="${{ secrets.POSTGRES_USER }}"/g' .env
        sed -i 's/POSTGRES_PASSWORD=""/POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"/g' .env
        sed -i 's/PGADMIN_DEFAULT_EMAIL=""/PGADMIN_DEFAULT_EMAIL="${{ secrets.PGADMIN_DEFAULT_EMAIL }}"/g' .env
        sed -i 's/PGADMIN_DEFAULT_PASSWORD=""/PGADMIN_DEFAULT_PASSWORD="${{ secrets.PGADMIN_DEFAULT_PASSWORD }}"/g' .env
        sed -i 's/GH_CLIENT_ID=""/GH_CLIENT_ID="${{ secrets.GH_CLIENT_ID }}"/g' .env
        sed -i 's/GH_CLIENT_SECRET=""/GH_CLIENT_SECRET="${{ secrets.GH_CLIENT_SECRET }}"/g' .env
        APP_API_ENDPOINT=$(sed 's:/:\\/:g' <<< ${{vars.APP_API_ENDPOINT}})
        sed -i "s/APP_API_ENDPOINT=\"\"/APP_API_ENDPOINT=\"$APP_API_ENDPOINT\"/g" .env
        GH_REDIRECT_URI=$(sed 's:/:\\/:g' <<< ${{vars.GH_REDIRECT_URI}})
        sed -i "s/GH_REDIRECT_URI=\"\"/GH_REDIRECT_URI=\"$GH_REDIRECT_URI\"/g" .env
        APP_UI_ENDPOINT=$(sed 's:/:\\/:g' <<< ${{vars.APP_UI_ENDPOINT}})
        sed -i "s/APP_UI_ENDPOINT=\"\"/APP_UI_ENDPOINT=\"$APP_UI_ENDPOINT\"/g" .env
    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.SSH_HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.SSH_USER }}
        docker_compose_prefix: undrfinde
        docker_compose_filename: docker-compose.yml

